name: 文書のリリース

on:
  push:
    tags:
      - "*/v[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  latex:
    name: LaTeX文書をコンパイル
    runs-on: macos-latest
    steps:
      - id: get-name
        run: |
          if [[ $GITHUB_REF_NAME =~ ^(.+)/v[0-9]+\.[0-9]+$ ]]; then
            echo name=${BASH_REMATCH[1]} >> $GITHUB_OUTPUT
          else
            exit 1
          fi
      - uses: actions/checkout@v6
      - run: sudo chown root /opt/homebrew/bin/gtar
      - run: sudo chmod u+s /opt/homebrew/bin/gtar
      - uses: actions/cache/restore@v4
        with:
          path: /usr/local/texlive
          key: 0
          enableCrossOsArchive: true
      - run: sudo /usr/local/texlive/2025/bin/universal-darwin/tlmgr path add
      - run: brew install graphviz
        if: steps.get-name.outputs.name == 'naibu'
      - run: latexmk -lualatex ${{steps.get-name.outputs.name}}.tex
        env:
          TZ: Asia/Tokyo
        working-directory: docs
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: docs/${{steps.get-name.outputs.name}}.pdf
